configure:
  languages:
    python: true
  plugins:
    - .aspect/cli/pytest_main.star

plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0
